run_config:
  name: random-forest-featset-1
  author: Jiusi Li
  version: default
  description: Classifies clouds into one of two types.
  dependencies: requirements.txt
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  output: artifacts

create_dataset:
  columns: 
    - visible_mean
    - visible_max
    - visible_min
    - visible_mean_distribution
    - visible_contrast
    - visible_entropy
    - visible_second_angular_momentum
    - IR_mean
    - IR_max
    - IR_min
  cloud_data_index:
    cloud1:
      - 53
      - 1077
    cloud2:
      - 1082
      - 2105

generate_features:
  calculate_range:
    IR_range:
      min_col: IR_min
      max_col: IR_max
  calculate_norm_range:
    IR_norm_range:
      min_col: IR_min
      max_col: IR_max
      mean_col: IR_mean
  log_transform:
    log_entropy: visible_entropy
  multiply:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy

analysis:
  font.size: 16
  axes.prop_cycle: cycler('color', ['#0085ca', '#888b8d', '#00c389', '#f4364c', '#e56db1'])
  xtick.labelsize: 14
  ytick.labelsize: 14
  figure.figsize: [12.0, 8.0]
  axes.labelsize: 20
  axes.labelcolor: '#677385'
  axes.titlesize: 20
  lines.color: '#0055A7'
  lines.linewidth: 3
  text.color: '#677385'
  font.family: sans-serif
  font.sans-serif: Tahoma

train_model:
  target: class
  test_size: 0.4
  initial_features:
    - log_entropy
    - IR_norm_range
    - entropy_x_contrast
  model_params:
    n_estimators: 10
    max_depth: 10

score_model:
  initial_features:
    - log_entropy
    - IR_norm_range
    - entropy_x_contrast

evaluate_performance:
  prob_col: "predicted_probability"
  bin_col: "predicted_binary"
  target: "class"

aws:
  upload: True
  bucket_name: jlv7143-clouds
  prefix: experiments/
