analysis:
  axes.labelcolor: '#677385'
  axes.labelsize: 20
  axes.prop_cycle: cycler('color', ['#0085ca', '#888b8d', '#00c389', '#f4364c', '#e56db1'])
  axes.titlesize: 20
  figure.figsize:
  - 12.0
  - 8.0
  font.family: sans-serif
  font.sans-serif: Tahoma
  font.size: 16
  lines.color: '#0055A7'
  lines.linewidth: 3
  text.color: '#677385'
  xtick.labelsize: 14
  ytick.labelsize: 14
aws:
  bucket_name: smf2659-clouds
  prefix: experiments
  upload: false
create_dataset:
  cloud_data_index:
    cloud1:
    - 53
    - 1077
    cloud2:
    - 1082
    - 2105
  columns:
  - visible_mean
  - visible_max
  - visible_min
  - visible_mean_distribution
  - visible_contrast
  - visible_entropy
  - visible_second_angular_momentum
  - IR_mean
  - IR_max
  - IR_min
evaluate_performance:
  bin_col: predicted_binary
  prob_col: predicted_probability
  target: class
generate_features:
  calculate_norm_range:
    IR_norm_range:
      max_col: IR_max
      mean_col: IR_mean
      min_col: IR_min
  calculate_range:
    IR_range:
      max_col: IR_max
      min_col: IR_min
  log_transform:
    log_entropy: visible_entropy
  multiply:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy
run_config:
  author: Michael Fedell
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  dependencies: requirements.txt
  description: Classifies clouds into one of two types.
  name: random-forest-featset-1
  output: artifacts
  version: default
score_model:
  initial_features:
  - log_entropy
  - IR_norm_range
  - entropy_x_contrast
train_model:
  initial_features:
  - log_entropy
  - IR_norm_range
  - entropy_x_contrast
  model_params:
    max_depth: 10
    n_estimators: 10
  target: class
  test_size: 0.4
